### ISSUE TITLE
Non-crit essential error

### ISSUE THREAD

**Issue by Anthraxmkv** [chaosvolt/cdda-tankmod-revived-mod#12]
DEBUG    : requested mission with uid 3 does not exist

 FUNCTION : find
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\mission.cpp
 LINE     : 78
 VERSION  : BN c2ebb51

This popped up when I choosed Tank commander as a profession.

**Comment by chaosvolt** [comment]
Huh, that's...odd. The scenario itself doesn't set any missions. My guess is it's doing something wacky when it tries to place the vehicle. Maybe because the vehicle placement is specifically in the scenario instead of the professions, and the only scenario that places a vehicle is The Last Delivery?

So if that's the case, I could either:
1. Add some sort of mission to the scenario, fixing this and giving the player a lil nudge towards potentially desirable content.
2. Simply shift the vehicle spawns to professions. Quicker and easier, and does allow me the ability to spawn other vehicles via different crew professions, but loses out on any interesting potential a mission might enable.
