### ISSUE TITLE
TRACKED flag does not exist

### ISSUE THREAD

**Issue by zack-shoylev** [chaosvolt/cdda-tankmod-revived-mod#3]
It seems CDDA added flag checking here https://github.com/CleverRaven/Cataclysm-DDA/commit/6b5a999477a56caafb7e5610aa690b7be65d736f#diff-f87f803ca1cc6ff999586c65c86345d647cdc693fd93bf705ab9c317dbe5355e

Is TRACKED supposed to be used for something?

**Comment by chaosvolt** [comment]
It's an old part from blazemod that was moved to tankmod due to being the only mod to ever use tracks.

Looking at the source, this appears to be a screwup on DDA's end. The code still references tracked part behavior here:
1. https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle.cpp#L5787
2. https://github.com/CleverRaven/Cataclysm-DDA/blob/acd99c66b21747c443eaecf978c958a3b1ca7e9f/src/veh_interact.cpp#L739

So either they need to fix their flag checking, or else remove tracked wheel behavior entirely. Tanks will practically still work more or less the same if I remove the flag, but the underlying problems here are definitely a DDA thing.

**Comment by ZhilkinSerg** [comment]
Please refrain from using words like "screwup" when referring to the project you were banned from. It is up to you as mod maintainer to fix the mod you maintain and in current case either add missing flag definition to json (see example in https://github.com/CleverRaven/Cataclysm-DDA/pull/49193) or use any other solution you can come up with to make mod work properly. We are not going to remove validity checks.

**Comment by chaosvolt** [comment]
It is definitely a code mistake to have behavior for a flag exist but not already have that flag defined in the repo's JSON. If defining the flag in flags.json will fix that, then I can do it if needed at the mod level, but since your code still uses it, it would be competent practice to have flags your code uses actually exist in your JSON.

**Comment by chaosvolt** [comment]
My criticisms of how this code is handled (and your off-topic mention of 5-years-old history in a discussion about flag usage and code) aside, thank you for notifying me that this issue could be resolved via a flag definition. I wasn't sure whether custom vehicle_part flags could be defined.

**Comment by ZhilkinSerg** [comment]
> 
> 
> It is definitely a code mistake to have behavior for a flag exist but not already have that flag defined in the repo's JSON. If defining the flag in flags.json will fix that, then I can do it if needed at the mod level, but since your code still uses it, it would be competent practice to have flags your code uses actually exist in your JSON.

Game code can (and actually does) support some flags which are not used in `dda` core mod and there is no sense in define these flags in `dda` core mod. Validation is done during JSON loading, so if a mod uses some flag it should be defined in JSON of that mod.

**Comment by chaosvolt** [comment]
Well, thank you for reminding me that defining the flag in the mod was a viable solution.
